import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>GoEarly</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>GoEarly</span>
        </h1>

        <p className={styles.description}>Get started by signing your wallet</p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Privacy</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus
              ipsum nunc, ultricies a odio dictum, congue mattis felis. Morbi et
              ultrices eros.
            </p>
          </a>

          <a className={styles.card}>
            <h2>Anonimity</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus
              ipsum nunc, ultricies a odio dictum, congue mattis felis. Morbi et
              ultrices eros.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at EthDenver🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
