import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Item from "../components/Item";
import styles from "../styles/Home.module.css";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import BuyBtn from "../components/BuyBtn";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>GoEarly</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={styles.grid}>
          {/* <Box
            component="form"
            sx={{
              "& > :not(style)": { m: 1, width: "36ch" },
            }}
            noValidate
            autoComplete="off"
          >
            <TextField
              id="standard-basic"
              label="Amount to Deposit"
              variant="standard"
            />
          </Box> */}
          <Item />
          <div>
            <h1>MOBA BUNDLE</h1>
            <h3>$25</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <BuyBtn />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at EthDenver🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
