export enum CHAIN {
  ETHEREUM ='ETHEREUM' ,
  POLYGON = 'POLYGON',
  // AVALANCHE = 'AVALANCHE',
  FANTOM = 'FANTOM',
  ARBITRUM = 'ARBITRUM',
  OPTIMISM = 'OPTIMISM',
  BSC = 'BSC',
  GOERLI = 'GOERLI',
}